"""Welsh Government announcements, written statements and consultations.

READ THIS BEFORE DEBUGGING A ZERO-RESULT RUN
--------------------------------------------
gov.wales sits behind a CloudFront WAF that **rejects requests from datacentre
IP ranges**. This was verified on 4 August 2026:

    GET https://www.gov.wales/announcements/rss
        -> HTTP 403, body "Request blocked. Generated by cloudfront"
    GET https://www.gov.wales/consultations
        -> HTTP 403

The feed itself is real and publicly advertised — gov.wales/announcements links
to it under "Follow us" — and the same URLs return 200 from an ordinary office
connection. The block is on where the request comes from, not on who is asking
or how often. Changing the User-Agent does not fix it and should not be
attempted: working around a WAF is both fragile and impolite.

There are therefore two supported routes, and the recommended production design
uses ROUTE B as primary with ROUTE A as an opportunistic supplement.

ROUTE A — direct RSS (`GovWalesRSSCollector`)
    Works when the collector runs from a network the WAF accepts: an NRLA
    office egress IP, an on-premises server, or an Azure deployment using a
    NAT gateway with a static IP that has been allow-listed. Cheapest and
    fastest when available. Fails cleanly and loudly when not.

ROUTE B — the official email subscription (`GovWalesMailboxCollector`)
    The Welsh Government offers an email subscription at
    gov.wales/subscribe/announcements, and Camlas's existing consultation
    alerts are themselves email notifications. Subscribing a dedicated NRLA
    shared mailbox and reading it via Microsoft Graph is:

      * sanctioned — it is the mechanism the publisher provides;
      * robust — no WAF, no scraping, no HTML parsing of a CMS;
      * already licensed — NRLA runs Microsoft 365, so there is nothing to buy;
      * auditable — the mailbox is a permanent record of what was notified
        and when, which matters if anyone later asks why a deadline was missed.

    This is not a workaround. For a policy team it is the better architecture,
    and it also replaces the consultation-alert half of the Camlas service
    outright.

The consultation deadline parser below is shared by both routes, because
closing dates are the single most actionable field in the whole system.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from datetime import date, datetime
from email.utils import parsedate_to_datetime

from ..models import Item, _clean
from .base import Collector


ANNOUNCEMENTS_RSS = "https://www.gov.wales/announcements/rss"
CONSULTATIONS_PAGE = "https://www.gov.wales/consultations"
SUBSCRIBE_PAGE = "https://www.gov.wales/subscribe/announcements"

DC = "{http://purl.org/dc/elements/1.1/}"

# gov.wales titles its items with a consistent prefix, which is how we classify
# them without needing to fetch each page.
KIND_PREFIXES = [
    (re.compile(r"^\s*written statement\s*[:\-]", re.I), "written_statement", "Written Statement"),
    (re.compile(r"^\s*oral statement\s*[:\-]", re.I), "written_statement", "Oral Statement"),
    (re.compile(r"^\s*cabinet statement\s*[:\-]", re.I), "written_statement", "Cabinet Statement"),
    (re.compile(r"^\s*consultation\s*[:\-]", re.I), "consultation", "Consultation"),
    (re.compile(r"\bconsultation\b", re.I), "consultation", "Consultation"),
    (re.compile(r"\bcall for evidence\b", re.I), "consultation", "Call for evidence"),
    (re.compile(r"^\s*statistical (release|first release)", re.I), "press_release", "Statistics"),
]

# Closing-date phrasings actually used on gov.wales consultation pages and in
# their notification emails.
DEADLINE_PATTERNS = [
    re.compile(r"clos(?:es|ing)\s*(?:date)?\s*[:\-]?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"clos(?:es|ing)\s*(?:on)?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"respond(?:\s*by|\s*before)\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"deadline\s*(?:for responses)?\s*[:\-]?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"until\s+(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"clos(?:es|ing)\s*(?:date)?\s*[:\-]?\s*(\d{4}-\d{2}-\d{2})", re.I),
]


def parse_deadline(text: str) -> date | None:
    """Extract a consultation closing date from free text.

    Returns None rather than guessing. A wrong deadline is worse than no
    deadline: it invites the team to plan around a date that does not exist.
    Where this returns None the dashboard shows "closing date not parsed —
    check the source", which is honest and still actionable.
    """
    if not text:
        return None
    for pattern in DEADLINE_PATTERNS:
        match = pattern.search(text)
        if not match:
            continue
        raw = match.group(1).strip()
        for fmt in ("%d %B %Y", "%d %b %Y", "%Y-%m-%d"):
            try:
                return datetime.strptime(raw, fmt).date()
            except ValueError:
                continue
    return None


def classify(title: str, body: str = "") -> tuple[str, str]:
    for pattern, kind, label in KIND_PREFIXES:
        if pattern.search(title):
            return kind, label
    if re.search(r"\bconsultation\b|\bcall for evidence\b", body, re.I):
        return "consultation", "Consultation"
    return "press_release", "Announcement"


# ---------------------------------------------------------------------------
# ROUTE A — direct RSS
# ---------------------------------------------------------------------------

class GovWalesRSSCollector(Collector):
    """Reads the public gov.wales announcements RSS feed.

    Will return nothing and log a clear explanation when run from a blocked
    network. That is by design: the run report shows the source as unavailable
    rather than implying the Welsh Government published nothing.
    """

    name = "gov_wales_rss"

    def collect(self, feed_url: str = ANNOUNCEMENTS_RSS):
        xml = self.fetcher.get_bytes(feed_url)
        if not xml:
            self.note_error(
                "gov.wales RSS unavailable from this host. This is expected on "
                "cloud infrastructure: the CloudFront WAF rejects datacentre "
                "IPs with HTTP 403. Use the mailbox route "
                "(GovWalesMailboxCollector) or run from the NRLA network. "
                f"Subscription page: {SUBSCRIBE_PAGE}"
            )
            return

        try:
            root = ET.fromstring(xml)
        except ET.ParseError as exc:
            self.note_error(f"gov.wales RSS was not valid XML: {exc}")
            return

        channel = root.find("channel")
        entries = channel.findall("item") if channel is not None else root.findall(
            "{http://www.w3.org/2005/Atom}entry")

        for entry in entries:
            yield from self._entry_to_items(entry)

    def _entry_to_items(self, entry: ET.Element):
        def get(tag: str) -> str:
            el = entry.find(tag)
            return (el.text or "").strip() if el is not None and el.text else ""

        title = get("title") or get("{http://www.w3.org/2005/Atom}title")
        if not title:
            return
        link = get("link") or ""
        description = get("description") or get("{http://www.w3.org/2005/Atom}summary")
        category = get("category")
        published = get("pubDate") or get("{http://www.w3.org/2005/Atom}updated")

        item_date = None
        if published:
            try:
                item_date = parsedate_to_datetime(published).date()
            except (TypeError, ValueError):
                try:
                    item_date = datetime.fromisoformat(
                        published.replace("Z", "+00:00")).date()
                except ValueError:
                    item_date = None

        kind, label = classify(title, description)
        combined = f"{title}\n{_clean(description)}"

        yield Item(
            source_kind=kind,
            source_name=f"Welsh Government — {label}",
            title=title,
            body=combined,
            url=link,
            item_date=item_date,
            forum="Welsh Government",
            agenda_item=category,
            deadline=parse_deadline(combined) if kind == "consultation" else None,
            raw_ref=ANNOUNCEMENTS_RSS,
        )


# ---------------------------------------------------------------------------
# ROUTE B — the official email subscription, read via Microsoft Graph
# ---------------------------------------------------------------------------

class GovWalesMailboxCollector(Collector):
    """Turns Welsh Government notification emails into monitored items.

    Design
    ------
    1. Subscribe a dedicated shared mailbox (e.g. senedd-monitor@nrla.org.uk)
       to gov.wales announcements and consultations, and forward Camlas-style
       alerts there during the transition so nothing is lost in the handover.
    2. Register an Entra ID application with the *application* permission
       ``Mail.Read`` scoped by an Exchange application access policy to that one
       mailbox. Scoping matters — without the policy the app can read every
       mailbox in the tenant, which IT will rightly refuse.
    3. This collector reads unprocessed messages, converts each to an Item, and
       marks them read so the next run does not reprocess them.

    Data protection
    ---------------
    Notification emails from gov.wales are machine-generated and contain no
    personal data beyond the sender address. This collector deliberately:
      * stores only subject, body and received date;
      * does NOT store recipient lists, headers or attachments;
      * ignores any message not from an allow-listed sender domain, so a
        misdirected human email to the shared mailbox is never ingested.
    Confirm the approach with NRLA's DPO before go-live; see the design note in
    the specification document.

    This class is intentionally transport-agnostic: `iter_messages` is the only
    method that touches Graph, so it can be swapped for an IMAP reader, or fed
    fixture dictionaries in tests, without changing the parsing logic.
    """

    name = "gov_wales_mailbox"

    ALLOWED_SENDER_DOMAINS = (
        "gov.wales", "llyw.cymru", "public-i.tv",
        "govdelivery.com", "service.gov.uk",
    )

    GRAPH_ROOT = "https://graph.microsoft.com/v1.0"

    def __init__(self, *args, mailbox: str = "", access_token: str = "",
                 **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.mailbox = mailbox
        self.access_token = access_token

    def iter_messages(self, top: int = 100):
        """Yield raw message dicts from Graph.

        Kept small and replaceable on purpose — everything below this line is
        pure parsing and is fully unit-testable without a tenant.
        """
        if not (self.mailbox and self.access_token):
            self.note_error(
                "mailbox route not configured (no mailbox/token supplied). "
                "This is the recommended production source for gov.wales; see "
                "the specification for the Entra ID app registration steps."
            )
            return

        url = (f"{self.GRAPH_ROOT}/users/{self.mailbox}/mailFolders/Inbox/messages"
               f"?$filter=isRead eq false&$top={top}"
               f"&$select=id,subject,body,bodyPreview,receivedDateTime,from,webLink")
        headers = {"Authorization": f"Bearer {self.access_token}"}
        while url:
            try:
                resp = self.fetcher.session.get(url, headers=headers, timeout=60)
            except Exception as exc:  # noqa: BLE001 - network variety
                self.note_error(f"Graph request failed: {exc}")
                return
            if resp.status_code != 200:
                self.note_error(f"Graph returned {resp.status_code}: {resp.text[:300]}")
                return
            payload = resp.json()
            yield from payload.get("value", [])
            url = payload.get("@odata.nextLink")

    def collect(self):
        for message in self.iter_messages():
            item = self.message_to_item(message)
            if item:
                yield item

    def message_to_item(self, message: dict) -> Item | None:
        sender = (message.get("from", {})
                  .get("emailAddress", {})
                  .get("address", "") or "").lower()
        if sender and not any(sender.endswith(d) or f"@{d}" in sender
                              for d in self.ALLOWED_SENDER_DOMAINS):
            # Silently ignore: a human emailing the shared mailbox is not
            # monitoring data and must not enter the archive.
            return None

        subject = (message.get("subject") or "").strip()
        body_obj = message.get("body") or {}
        body = _clean(body_obj.get("content") or message.get("bodyPreview") or "")
        if not subject and not body:
            return None

        received = None
        if raw := message.get("receivedDateTime"):
            try:
                received = datetime.fromisoformat(
                    raw.replace("Z", "+00:00")).date()
            except ValueError:
                received = None

        kind, label = classify(subject, body)
        combined = f"{subject}\n{body}"

        # Prefer a real gov.wales link found in the email over the Outlook
        # webLink, so dashboard links go to the source, not to a mailbox.
        link = ""
        if urls := re.findall(r"https?://(?:www\.)?(?:gov\.wales|llyw\.cymru)/[^\s\"'<>)]+",
                              body):
            link = urls[0].rstrip(".,);")

        return Item(
            source_kind=kind,
            source_name=f"Welsh Government — {label} (notification)",
            title=subject or label,
            body=combined,
            url=link,
            item_date=received,
            forum="Welsh Government",
            deadline=parse_deadline(combined) if kind == "consultation" else None,
            raw_ref=f"mailbox:{self.mailbox}:{message.get('id','')}",
        )
