"""Welsh Government announcements, written statements and consultations.

READ THIS BEFORE DEBUGGING A ZERO-RESULT RUN
--------------------------------------------
gov.wales sits behind a CloudFront WAF that **rejects requests from datacentre
IP ranges**. This was verified on 4 August 2026:

    GET https://www.gov.wales/announcements/rss
        -> HTTP 403, body "Request blocked. Generated by cloudfront"
    GET https://www.gov.wales/consultations
        -> HTTP 403

The feed itself is real and publicly advertised — gov.wales/announcements links
to it under "Follow us" — and the same URLs return 200 from an ordinary office
connection. The block is on where the request comes from, not on who is asking
or how often. Changing the User-Agent does not fix it and should not be
attempted: working around a WAF is both fragile and impolite.

**That block was not permanent.** On 11 September 2026 www.gov.wales answered
GitHub's runners normally again — the RSS feed above returned a hundred items
from the same host that had refused it for weeks. Whether that is a settled
change or a temporary one is not knowable from here, so every route below
stays, and each one says so out loud when it stops working rather than going
quiet.

There are therefore four supported routes. ROUTE D reads the consultation
register directly and is the only one that carries authoritative closing dates;
ROUTE C works everywhere and needs nothing set up; ROUTE B is the durable
answer if the block returns; ROUTE A is an opportunistic supplement.

ROUTE A — direct RSS (`GovWalesRSSCollector`)
    Works when the collector runs from a network the WAF accepts: an NRLA
    office egress IP, an on-premises server, or an Azure deployment using a
    NAT gateway with a static IP that has been allow-listed. Cheapest and
    fastest when available. Fails cleanly and loudly when not.

ROUTE B — the official email subscription (`GovWalesMailboxCollector`)
    The Welsh Government offers an email subscription at
    gov.wales/subscribe/announcements, and Camlas's existing consultation
    alerts are themselves email notifications. Subscribing a dedicated NRLA
    shared mailbox and reading it via Microsoft Graph is:

      * sanctioned — it is the mechanism the publisher provides;
      * robust — no WAF, no scraping, no HTML parsing of a CMS;
      * already licensed — NRLA runs Microsoft 365, so there is nothing to buy;
      * auditable — the mailbox is a permanent record of what was notified
        and when, which matters if anyone later asks why a deadline was missed.

    This is not a workaround. For a policy team it is the better architecture,
    and it also replaces the consultation-alert half of the Camlas service
    outright.

ROUTE C — the Welsh Government newsroom (`GovWalesNewsroomCollector`)
    `media.service.gov.wales` is a *different host* from www.gov.wales and is
    not behind the CloudFront rule. Measured 19 August 2026 and again on
    11 September 2026, it returns 200 from a cloud host. It is the Welsh
    Government's own newsroom carrying the same press notices, tagged by topic.

    It needs no account, no permission and no IT ticket, which is why it runs
    on every run and why the Welsh Government section of the page is no longer
    empty. What it does NOT carry is the consultation *register* — the
    authoritative closing dates — so ROUTE B is still worth setting up, and the
    page says so out loud rather than leaving a reader to assume full coverage.

The consultation deadline parser below is shared by all three routes, because
closing dates are the single most actionable field in the whole system.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from datetime import date, datetime, timedelta, timezone
from email.utils import parsedate_to_datetime

from bs4 import BeautifulSoup

from ..models import Item, _clean
from .base import Collector


ANNOUNCEMENTS_RSS = "https://www.gov.wales/announcements/rss"
CONSULTATIONS_PAGE = "https://www.gov.wales/consultations"
SUBSCRIBE_PAGE = "https://www.gov.wales/subscribe/announcements"

# The Welsh Government's own newsroom. A DIFFERENT HOST from www.gov.wales and
# — measured 19 August 2026, re-measured 11 September 2026 — not behind the
# CloudFront rule that makes www.gov.wales unreachable from a cloud host:
#
#     GET https://www.gov.wales/announcements/rss   -> 403
#     GET https://www.gov.wales/consultations       -> 403
#     GET https://media.service.gov.wales/news      -> 200
#
# It carries the same press notices, tagged by topic. Nothing is being worked
# around: this is a second public address published by the same body, fetched
# with the same honest User-Agent and the same 1.5s request floor as every
# other source. If it is ever put behind the same rule, this collector fails
# loudly (see the two note_error calls below) rather than going quiet.
NEWSROOM_ROOT = "https://media.service.gov.wales"
NEWSROOM_NEWS = f"{NEWSROOM_ROOT}/news"

DC = "{http://purl.org/dc/elements/1.1/}"

# gov.wales titles its items with a consistent prefix, which is how we classify
# them without needing to fetch each page.
KIND_PREFIXES = [
    (re.compile(r"^\s*written statement\s*[:\-]", re.I), "written_statement", "Written Statement"),
    (re.compile(r"^\s*oral statement\s*[:\-]", re.I), "written_statement", "Oral Statement"),
    (re.compile(r"^\s*cabinet statement\s*[:\-]", re.I), "written_statement", "Cabinet Statement"),
    (re.compile(r"^\s*consultation\s*[:\-]", re.I), "consultation", "Consultation"),
    (re.compile(r"\bconsultation\b", re.I), "consultation", "Consultation"),
    (re.compile(r"\bcall for evidence\b", re.I), "consultation", "Call for evidence"),
    (re.compile(r"^\s*statistical (release|first release)", re.I), "press_release", "Statistics"),
]

# Closing-date phrasings actually used on gov.wales consultation pages and in
# their notification emails.
DEADLINE_PATTERNS = [
    re.compile(r"clos(?:es|ing)\s*(?:date)?\s*[:\-]?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"clos(?:es|ing)\s*(?:on)?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"respond(?:\s*by|\s*before)\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"deadline\s*(?:for responses)?\s*[:\-]?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"until\s+(\d{1,2}\s+\w+\s+\d{4})", re.I),
    re.compile(r"clos(?:es|ing)\s*(?:date)?\s*[:\-]?\s*(\d{4}-\d{2}-\d{2})", re.I),
    # The consultation register's own wording, which none of the patterns above
    # matched: every gov.wales consultation page carries "Consultation ends:"
    # and that line IS the authoritative closing date.
    re.compile(r"consultation\s+ends\s*[:\-]?\s*(\d{1,2}\s+\w+\s+\d{4})", re.I),
]


def parse_deadline(text: str) -> date | None:
    """Extract a consultation closing date from free text.

    Returns None rather than guessing. A wrong deadline is worse than no
    deadline: it invites the team to plan around a date that does not exist.
    Where this returns None the dashboard shows "closing date not parsed —
    check the source", which is honest and still actionable.
    """
    if not text:
        return None
    for pattern in DEADLINE_PATTERNS:
        match = pattern.search(text)
        if not match:
            continue
        raw = match.group(1).strip()
        for fmt in ("%d %B %Y", "%d %b %Y", "%Y-%m-%d"):
            try:
                return datetime.strptime(raw, fmt).date()
            except ValueError:
                continue
    return None


def _one_line(text: str) -> str:
    """Collapse a title onto one line.

    `_clean` normalises spaces and tabs but deliberately keeps newlines, which
    is right for a body and wrong for a heading: an anchor wrapped across two
    lines in the source produced a title with a line break in the middle of it,
    which then appeared that way on the page and in the email.
    """
    return re.sub(r"\s+", " ", _clean(text)).strip()


def classify(title: str, body: str = "") -> tuple[str, str]:
    for pattern, kind, label in KIND_PREFIXES:
        if pattern.search(title):
            return kind, label
    if re.search(r"\bconsultation\b|\bcall for evidence\b", body, re.I):
        return "consultation", "Consultation"
    return "press_release", "Announcement"


# ---------------------------------------------------------------------------
# ROUTE A — direct RSS
# ---------------------------------------------------------------------------

class GovWalesRSSCollector(Collector):
    """Reads the public gov.wales announcements RSS feed.

    Will return nothing and log a clear explanation when run from a blocked
    network. That is by design: the run report shows the source as unavailable
    rather than implying the Welsh Government published nothing.
    """

    name = "gov_wales_rss"

    def collect(self, feed_url: str = ANNOUNCEMENTS_RSS):
        xml = self.fetcher.get_bytes(feed_url)
        if not xml:
            self.note_error(
                "gov.wales RSS unavailable from this host. This is expected on "
                "cloud infrastructure: the CloudFront WAF rejects datacentre "
                "IPs with HTTP 403. Use the mailbox route "
                "(GovWalesMailboxCollector) or run from the NRLA network. "
                f"Subscription page: {SUBSCRIBE_PAGE}"
            )
            return

        try:
            root = ET.fromstring(xml)
        except ET.ParseError as exc:
            self.note_error(f"gov.wales RSS was not valid XML: {exc}")
            return

        channel = root.find("channel")
        entries = channel.findall("item") if channel is not None else root.findall(
            "{http://www.w3.org/2005/Atom}entry")

        for entry in entries:
            yield from self._entry_to_items(entry)

    def _entry_to_items(self, entry: ET.Element):
        def get(tag: str) -> str:
            el = entry.find(tag)
            return (el.text or "").strip() if el is not None and el.text else ""

        title = get("title") or get("{http://www.w3.org/2005/Atom}title")
        if not title:
            return
        link = get("link") or ""
        description = get("description") or get("{http://www.w3.org/2005/Atom}summary")
        category = get("category")
        published = get("pubDate") or get("{http://www.w3.org/2005/Atom}updated")

        item_date = None
        if published:
            try:
                item_date = parsedate_to_datetime(published).date()
            except (TypeError, ValueError):
                try:
                    item_date = datetime.fromisoformat(
                        published.replace("Z", "+00:00")).date()
                except ValueError:
                    item_date = None

        kind, label = classify(title, description)
        combined = f"{title}\n{_clean(description)}"

        yield Item(
            source_kind=kind,
            source_name=f"Welsh Government — {label}",
            title=title,
            body=combined,
            url=link,
            item_date=item_date,
            forum="Welsh Government",
            agenda_item=category,
            deadline=parse_deadline(combined) if kind == "consultation" else None,
            raw_ref=ANNOUNCEMENTS_RSS,
        )


    # -- for the morning briefing ---------------------------------------------

    # A statement given in the Chamber is published afterwards as "Oral
    # Statement: ...". It is a record of Plenary, which the debate summaries
    # cover, not an announcement — Camlas leave them out too.
    _NOT_ANNOUNCEMENTS = re.compile(r"^\s*oral statement\s*[:\-]", re.I)

    def recent(self, since_utc: datetime, max_articles: int = 20,
               feed_url: str = ANNOUNCEMENTS_RSS
               ) -> list[tuple[datetime | None, Item, str]]:
        """Announcements published at or after ``since_utc`` (naive UTC).

        Returns ``(published_utc, item, lead)`` like the newsroom's
        ``recent``. The feed is the ONLY source of written statements: the
        newsroom carries press notices only. On 24 September 2026 the
        supplier's briefing listed "Written Statement: Learning Disability
        Transformation Programme 2026-2029" and this one did not, because it
        read the newsroom alone.

        The lead is read from the page itself — the feed has no description.
        For a written statement it is the statement's first paragraph, and the
        minister's name line goes on ``item.speaker``.
        """
        text = self.fetcher.get_text(feed_url)
        if not text:
            self.note_error(
                "The gov.wales announcements feed could not be read, so written "
                "statements are missing from this briefing. (gov.wales has at "
                "times refused requests from cloud servers.)")
            return []
        try:
            root = ET.fromstring(text.encode("utf-8") if isinstance(text, str) else text)
        except ET.ParseError as exc:
            self.note_error(f"The gov.wales announcements feed was not valid XML: {exc}")
            return []

        found: list[tuple[datetime | None, Item, str]] = []
        budget = max_articles
        for entry in root.iter("item"):
            title = (entry.findtext("title") or "").strip()
            if not title or self._NOT_ANNOUNCEMENTS.search(title):
                continue
            try:
                at = parsedate_to_datetime(entry.findtext("pubDate") or "")
                at = at.astimezone(timezone.utc).replace(tzinfo=None)
            except (TypeError, ValueError):
                continue
            if at < since_utc:
                continue
            item = next(self._entry_to_items(entry), None)
            if item is None:
                continue
            item.url = _strip_tracking(item.url)
            lead = ""
            if budget > 0:
                budget -= 1
                lead, minister = self._lead_from_page(item.url)
                if minister:
                    item.speaker = minister
                if lead:
                    item.body = f"{item.title}\n{lead}"
            item.points = [lead] if lead else []
            found.append((at, item, lead))
        found.sort(key=lambda t: t[0], reverse=True)
        return found

    def _lead_from_page(self, url: str) -> tuple[str, str]:
        """``(first paragraph, minister line)`` from a gov.wales page."""
        html = self.fetcher.get_text(url) if url else None
        if not html:
            return "", ""
        soup = BeautifulSoup(html, "html.parser")
        paras = [_clean(p.get_text(" ", strip=True))
                 for p in soup.select(".page-content p") or soup.select("article p")]
        paras = [p for p in paras if p]
        minister = ""
        if paras and _MINISTER_LINE.match(paras[0]):
            minister, paras = paras[0], paras[1:]
        if paras:
            return paras[0], minister
        meta = soup.select_one('meta[name="description"]')
        return (_clean(meta.get("content", "")) if meta else ""), minister


# "Mabon ap Gwynfor MS, Cabinet Minister for Health and Care"
_MINISTER_LINE = re.compile(
    r"^[^.]{3,80}\b(MS|AS)\b,\s*(First Minister|Deputy First Minister|"
    r"(Cabinet |Deputy )?(Minister|Secretary)|Counsel General|Trefnydd)\b[^.]{0,120}$")


def _strip_tracking(url: str) -> str:
    """gov.wales feed links carry utm_* parameters; the page is the same
    without them, and a clean link is what should be in an email."""
    return re.sub(r"\?utm_[^#]*", "", url or "")


# ---------------------------------------------------------------------------
# ROUTE B — the official email subscription, read via Microsoft Graph
# ---------------------------------------------------------------------------

class GovWalesMailboxCollector(Collector):
    """Turns Welsh Government notification emails into monitored items.

    Design
    ------
    1. Subscribe a dedicated shared mailbox (e.g. joshua.helm-cowley@nrla.org.uk)
       to gov.wales announcements and consultations, and forward Camlas-style
       alerts there during the transition so nothing is lost in the handover.
    2. Register an Entra ID application with the *application* permission
       ``Mail.Read`` scoped by an Exchange application access policy to that one
       mailbox. Scoping matters — without the policy the app can read every
       mailbox in the tenant, which IT will rightly refuse.
    3. This collector reads messages RECEIVED SINCE a given date, and converts
       each to an Item.

    Why by date, and not by the unread flag
    ---------------------------------------
    The first version filtered on ``isRead eq false`` and marked each message
    read. The mailbox is a real person's inbox, so opening a Welsh Government
    email in Outlook — the entirely normal thing to do with an email — removed
    it from the collector's view permanently. The consultation was then missing
    from the page, and nothing anywhere said so.

    Reading by ``receivedDateTime`` also keeps the permission ask at
    ``Mail.Read`` rather than ``Mail.ReadWrite``, because nothing has to be
    written back. That is a materially smaller thing to ask IT for, and IT are
    right to care about the difference.

    Data protection
    ---------------
    Notification emails from gov.wales are machine-generated and contain no
    personal data beyond the sender address. This collector deliberately:
      * stores only subject, body and received date;
      * does NOT store recipient lists, headers or attachments;
      * ignores any message not from an allow-listed sender domain, so a
        misdirected human email to the shared mailbox is never ingested.
    Confirm the approach with NRLA's DPO before go-live; see the design note in
    the specification document.

    This class is intentionally transport-agnostic: `iter_messages` is the only
    method that touches Graph, so it can be swapped for an IMAP reader, or fed
    fixture dictionaries in tests, without changing the parsing logic.
    """

    name = "gov_wales_mailbox"

    ALLOWED_SENDER_DOMAINS = (
        "gov.wales", "llyw.cymru", "public-i.tv",
        "govdelivery.com", "service.gov.uk",
    )

    GRAPH_ROOT = "https://graph.microsoft.com/v1.0"

    def __init__(self, *args, mailbox: str = "", access_token: str = "",
                 **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.mailbox = mailbox
        self.access_token = access_token

    def first_page_url(self, since: date | None = None, top: int = 100) -> str:
        """Build the Graph query for the first page of messages.

        Separated out and given no side effects purely so it can be asserted
        on in a test. The bug this replaces lived in a single f-string buried
        inside a paging loop that needed a tenant to exercise, which is how it
        survived review.
        """
        since = since or (date.today() - timedelta(days=21))
        return (f"{self.GRAPH_ROOT}/users/{self.mailbox}/mailFolders/Inbox/messages"
                f"?$filter=receivedDateTime ge {since.isoformat()}T00:00:00Z"
                f"&$top={top}"
                f"&$orderby=receivedDateTime desc"
                f"&$select=id,subject,body,bodyPreview,receivedDateTime,from,webLink")

    def iter_messages(self, since: date | None = None, top: int = 100):
        """Yield raw message dicts from Graph.

        Kept small and replaceable on purpose — everything below this line is
        pure parsing and is fully unit-testable without a tenant.
        """
        if not (self.mailbox and self.access_token):
            self.note_error(
                "mailbox route not configured (no mailbox/token supplied). "
                "This closes the gov.wales consultation-register gap; see "
                "WELSH-GOVERNMENT-SETUP.md for the four repository secrets."
            )
            return

        url = self.first_page_url(since=since, top=top)
        headers = {"Authorization": f"Bearer {self.access_token}"}
        while url:
            try:
                resp = self.fetcher.session.get(url, headers=headers, timeout=60)
            except Exception as exc:  # noqa: BLE001 - network variety
                self.note_error(f"Graph request failed: {exc}")
                return
            if resp.status_code != 200:
                self.note_error(self._explain_status(resp))
                return
            payload = resp.json()
            yield from payload.get("value", [])
            url = payload.get("@odata.nextLink")

    def _explain_status(self, resp) -> str:
        """Say what a Graph failure means to the person who has to fix it.

        401 and 403 look identical in a log and have completely different
        causes and completely different fixes — and the fix for one of them is
        a message to IT, so guessing wastes days rather than minutes.
        """
        body = (resp.text or "")[:300]
        if resp.status_code == 401:
            return (
                "Microsoft Graph returned 401 (unauthorised) for the mailbox "
                "route. The credential was rejected: either the client secret "
                "has expired, or admin consent for the application permission "
                "Mail.Read was never granted — in Azure, the API permissions "
                "screen must show a green tick in the Status column. "
                f"Graph said: {body}")
        if resp.status_code == 403:
            return (
                "Microsoft Graph returned 403 (forbidden) for the mailbox "
                "route. The app signed in successfully but is not allowed to "
                "read this mailbox. Usually the Exchange application access "
                f"policy names a different mailbox from MONITOR_MAILBOX "
                f"({self.mailbox}), or the permission granted was a delegated "
                "one rather than an application one. "
                f"Graph said: {body}")
        return f"Graph returned {resp.status_code}: {body}"

    def collect(self, since: date | None = None):
        for message in self.iter_messages(since=since):
            item = self.message_to_item(message)
            if item:
                yield item

    def message_to_item(self, message: dict) -> Item | None:
        sender = (message.get("from", {})
                  .get("emailAddress", {})
                  .get("address", "") or "").lower()
        if sender and not any(sender.endswith(d) or f"@{d}" in sender
                              for d in self.ALLOWED_SENDER_DOMAINS):
            # Silently ignore: a human emailing the shared mailbox is not
            # monitoring data and must not enter the archive.
            return None

        subject = (message.get("subject") or "").strip()
        body_obj = message.get("body") or {}
        body = _clean(body_obj.get("content") or message.get("bodyPreview") or "")
        if not subject and not body:
            return None

        received = None
        if raw := message.get("receivedDateTime"):
            try:
                received = datetime.fromisoformat(
                    raw.replace("Z", "+00:00")).date()
            except ValueError:
                received = None

        kind, label = classify(subject, body)
        combined = f"{subject}\n{body}"

        # Prefer a real gov.wales link found in the email over the Outlook
        # webLink, so dashboard links go to the source, not to a mailbox.
        link = ""
        if urls := re.findall(r"https?://(?:www\.)?(?:gov\.wales|llyw\.cymru)/[^\s\"'<>)]+",
                              body):
            link = urls[0].rstrip(".,);")

        return Item(
            source_kind=kind,
            source_name=f"Welsh Government — {label} (notification)",
            title=subject or label,
            body=combined,
            url=link,
            item_date=received,
            forum="Welsh Government",
            deadline=parse_deadline(combined) if kind == "consultation" else None,
            raw_ref=f"mailbox:{self.mailbox}:{message.get('id','')}",
        )


# ---------------------------------------------------------------------------
# ROUTE C — the Welsh Government newsroom, reachable from anywhere
# ---------------------------------------------------------------------------

class GovWalesNewsroomCollector(Collector):
    """Welsh Government press notices from media.service.gov.wales.

    This is the route that finally put Welsh Government material on the page.
    Neither of the other two could: RSS is blocked from any cloud host, and the
    mailbox route needs an app registration from IT that may take weeks.

    What it does NOT close
    ----------------------
    The consultation register at gov.wales/consultations holds the
    *authoritative* closing dates, and that register is still unreachable. A
    consultation is normally announced in the newsroom when it opens, so it is
    usually seen — but the deadline parsed out of an announcement should be
    confirmed against gov.wales before anyone plans around it. That limitation
    is stated on the page itself, in the "What this page does not cover" panel,
    rather than being left for a reader to discover.

    Politeness
    ----------
    Twelve cards a page, one page fetched at a time, at most MAX_PAGES pages
    and MAX_ARTICLES full articles per run, all through the shared Fetcher and
    therefore behind the same 1.5s-per-host floor. A full run is well under a
    hundred requests to a press office that serves far more than that a minute.
    """

    name = "gov_wales_newsroom"
    source_kind = "press_release"

    # Roughly three months at the newsroom's usual publishing rate. Deliberately
    # more than the 21-day lookback, so a re-dated or late-appearing story is
    # still found.
    MAX_PAGES = 6

    # Cards carry a one-paragraph summary, which is too thin for the taxonomy to
    # score fairly — "Building Safety (Wales) Act 2026" can appear only in the
    # body. So each in-window card is fetched in full, capped so a busy
    # fortnight cannot turn one run into four hundred requests.
    MAX_ARTICLES = 40

    # "Wednesday 19 Aug 2026, 14:00" on a card; "2026-06-17 14:00" in the
    # datetime attribute of a story page.
    CARD_DATE_FORMAT = "%A %d %b %Y, %H:%M"
    STORY_DATE_FORMAT = "%Y-%m-%d %H:%M"

    def collect(self, since: date | None = None, max_articles: int | None = None):
        start = since or (date.today() - timedelta(days=21))
        budget = self.MAX_ARTICLES if max_articles is None else max_articles

        seen: set[str] = set()
        for page in range(1, self.MAX_PAGES + 1):
            url = NEWSROOM_NEWS if page == 1 else f"{NEWSROOM_NEWS}?page={page}"
            html = self.fetcher.get_text(url)

            if html is None:
                if page == 1:
                    # Loud failure #1. If this host has since been put behind
                    # the same rule as www.gov.wales, the Welsh Government half
                    # of the page is gone and someone must be told — an empty
                    # section is indistinguishable from a quiet fortnight.
                    self.note_error(
                        "The Welsh Government newsroom at "
                        f"{NEWSROOM_NEWS} could not be fetched. If this is a "
                        "403, the host has been put behind the same CloudFront "
                        "rule as www.gov.wales and this route is dead — the "
                        "mailbox route (WELSH-GOVERNMENT-SETUP.md) is then the "
                        "only way to see Welsh Government announcements.")
                return

            cards = self._parse_cards(html)

            if page == 1 and not cards:
                # Loud failure #2, and a separate one on purpose. Page 1
                # answering 200 with nothing parseable means the markup has
                # changed, which is a different problem with a different fix
                # from the host being blocked — and it is the failure most
                # likely to masquerade as a quiet fortnight.
                self.note_error(
                    "The Welsh Government newsroom returned a page but no "
                    "stories could be read from it — the markup has probably "
                    "changed. The parser expects a '.card' per story, with "
                    "'.card__date', '.card__title' and an 'a.card__link'. "
                    "Until this is fixed the Welsh Government section is "
                    "empty for the wrong reason.")
                return

            in_window = [c for c in cards if c["date"] and c["date"] >= start]

            for card in in_window:
                if card["slug"] in seen:
                    continue
                seen.add(card["slug"])
                if budget <= 0:
                    break
                budget -= 1
                item = self._story_to_item(card)
                if item:
                    yield item

            # Everything on this page predates the window, so every later page
            # does too — the listing is newest first.
            if cards and not in_window:
                return
            if not cards:
                return

    # -- parsing -----------------------------------------------------------

    def _parse_cards(self, html: str) -> list[dict]:
        """Turn a listing page into card dicts. Never raises."""
        soup = BeautifulSoup(html, "html.parser")
        cards: list[dict] = []

        for node in soup.select(".card"):
            link = node.select_one("a.card__link") or node.select_one("a[href]")
            if not link:
                continue
            href = (link.get("href") or "").strip()
            # Topic links (/news/t/housing) sit in the same markup as stories
            # and are not stories. Following them yields a listing page parsed
            # as if it were an announcement.
            if not href.startswith("/news/") or href.startswith("/news/t/"):
                continue

            title = _one_line(link.get_text(" ", strip=True))
            if not title:
                continue

            summary_node = node.select_one(".card__summary")
            summary = _clean(summary_node.get_text(" ", strip=True)) if summary_node else ""
            # The summary is usually two or three bullet points with no full
            # stops, so joined into one string it runs on: "…from their car
            # Roadside rubbish blights communities…". The first point on its
            # own is the notice's own headline sentence.
            lead = ""
            points: list[str] = []
            if summary_node:
                first = summary_node.find(["li", "p"])
                lead = _clean(first.get_text(" ", strip=True)) if first else ""
                points = [_clean(x.get_text(" ", strip=True))
                          for x in summary_node.find_all(["li", "p"])]
                points = [x for x in points if x]

            date_node = node.select_one(".card__date") or node.select_one("time")
            date_text = date_node.get_text(" ", strip=True) if date_node else ""
            card_date = self._parse_card_date(date_text)

            cards.append({
                "slug": href.rsplit("/", 1)[-1],
                "url": f"{NEWSROOM_ROOT}{href}",
                "title": title,
                "summary": summary,
                "date": card_date,
                "at": self._parse_card_time(date_text),
                "lead": lead or summary,
                "points": points or ([summary] if summary else []),
            })
        return cards

    def _parse_card_date(self, text: str) -> date | None:
        text = (text or "").strip()
        if not text:
            return None
        try:
            return datetime.strptime(text, self.CARD_DATE_FORMAT).date()
        except ValueError:
            pass
        # Without the weekday, and without the time, in case either is dropped.
        for fmt in ("%d %b %Y, %H:%M", "%A %d %b %Y", "%d %b %Y", "%d %B %Y"):
            try:
                return datetime.strptime(text, fmt).date()
            except ValueError:
                continue
        return None

    def _parse_card_time(self, text: str) -> datetime | None:
        """The card's full timestamp, in UTC, or None if it carries no time.

        The newsroom prints times in UTC. "Monday 21 Sep 2026, 23:00" is the
        Programme for Government, embargoed to one minute past midnight on
        Tuesday 22 September British Summer Time. A reader in Cardiff saw it on
        the Tuesday, and the morning briefing has to agree with them — which it
        cannot do from a date alone.
        """
        try:
            return datetime.strptime((text or "").strip(), self.CARD_DATE_FORMAT)
        except ValueError:
            return None

    def recent(self, since_utc: datetime,
               max_articles: int = 30) -> list[tuple[datetime | None, Item, str]]:
        """Stories published at or after ``since_utc``, newest first.

        For the morning briefing, which needs "since the last briefing went
        out" rather than "since a date". Returns ``(published_utc, item,
        lead)`` — the lead being the card's first summary point, verbatim. A
        card with no time is judged on its date alone, generously. Loud on
        failure in exactly the same two ways as `collect`.
        """
        found: list[tuple[datetime | None, Item, str]] = []
        budget = max_articles
        for page in range(1, self.MAX_PAGES + 1):
            url = NEWSROOM_NEWS if page == 1 else f"{NEWSROOM_NEWS}?page={page}"
            html = self.fetcher.get_text(url)
            if html is None:
                if page == 1:
                    self.note_error(
                        f"The Welsh Government newsroom at {NEWSROOM_NEWS} could "
                        "not be fetched, so the briefing has no Welsh "
                        "Government section today.")
                return found
            cards = self._parse_cards(html)
            if page == 1 and not cards:
                self.note_error(
                    "The Welsh Government newsroom returned a page but no "
                    "stories could be read from it — the markup has probably "
                    "changed.")
                return found

            def in_window(card: dict) -> bool:
                if card.get("at") is not None:
                    return card["at"] >= since_utc
                return bool(card["date"]) and card["date"] >= since_utc.date()

            fresh = [c for c in cards if in_window(c)]
            for card in fresh:
                if budget <= 0:
                    return found
                budget -= 1
                item = self._story_to_item(card)
                if item:
                    # The card's bullet points, verbatim, for the press
                    # release alert. An attribute rather than an Item field,
                    # so the archive's schema is untouched.
                    item.points = card.get("points", [])
                    found.append((card.get("at"), item, card.get("lead", "")))
            if not fresh or len(fresh) < len(cards):
                # Newest first: once a card falls outside the window, every
                # card after it does too.
                return found
        return found

    def _story_to_item(self, card: dict) -> Item | None:
        html = self.fetcher.get_text(card["url"])
        if html is None:
            # One unreachable story is not worth a run-level error, but the
            # card summary is better than nothing.
            return self._item_from(card, body=card["summary"], tags=[],
                                   story_date=None)

        soup = BeautifulSoup(html, "html.parser")

        body_node = soup.select_one(".story__body")
        summary_node = soup.select_one(".story__summary")
        parts = [card["summary"]]
        if summary_node:
            parts.append(summary_node.get_text(" ", strip=True))
        if body_node:
            parts.append(body_node.get_text("\n", strip=True))
        body = _clean("\n\n".join(p for p in parts if p))

        tags = [t.get_text(" ", strip=True)
                for t in soup.select(".story__tags a, .tag__link")]

        story_date = None
        date_node = soup.select_one("time.story__date") or soup.select_one("time")
        if date_node:
            raw = (date_node.get("datetime") or "").strip()
            for fmt in (self.STORY_DATE_FORMAT, "%Y-%m-%d"):
                try:
                    story_date = datetime.strptime(raw, fmt).date()
                    break
                except ValueError:
                    continue
            if story_date is None:
                story_date = self._parse_card_date(
                    date_node.get_text(" ", strip=True))

        return self._item_from(card, body=body, tags=tags, story_date=story_date)

    def _item_from(self, card: dict, body: str, tags: list[str],
                   story_date: date | None) -> Item:
        # The story page wins. A listing entry can be re-dated when a notice is
        # edited, and the date on the notice itself is the one a reader would
        # cite.
        item_date = story_date or card["date"]
        kind, label = classify(card["title"], body)
        combined = f"{card['title']}\n{body}"

        return Item(
            source_kind=kind,
            source_name=f"Welsh Government — {label}",
            title=card["title"],
            body=combined,
            url=card["url"],
            item_date=item_date,
            forum="Welsh Government",
            agenda_item="; ".join(tags),
            deadline=parse_deadline(combined) if kind == "consultation" else None,
            raw_ref=f"newsroom:{card['slug']}",
        )


# ---------------------------------------------------------------------------
# ROUTE D — the consultation register itself
# ---------------------------------------------------------------------------

class GovWalesConsultationsCollector(Collector):
    """Open consultations from gov.wales/consultations.

    WHY THIS EXISTS, AND WHY IT MIGHT STOP WORKING
    ----------------------------------------------
    This is the register the whole Welsh Government half of the tool has been
    working around. It holds the authoritative closing dates, and on
    11 September 2026 the first Friday email was compared against the supplier
    briefing it replaces and was missing four consultations from it — every one
    of them core NRLA business:

        Rent Guarantor Guidance for Local Housing Authorities     19 Oct
        Codes of practice for the management of student accommodation  25 Sep
        Council Tax Reduction Scheme: reassessment thresholds     23 Sep
        Classification of self-catering properties for local tax  23 Oct

    None had a newsroom announcement, so no other route could see them.

    The register sits on www.gov.wales, which rejected datacentre IPs for
    weeks — that block is the reason `GovWalesRSSCollector` exists in the shape
    it does. On 11 September 2026 it answered GitHub's runners normally. That
    may be a permanent change or it may not, so this collector is written to
    fail loudly rather than quietly: if the block returns, the run says so and
    the page's coverage banner names it, instead of the consultations simply
    ceasing to appear. WELSH-GOVERNMENT-SETUP.md stays in the repository so
    that the mailbox route can be set up later if that happens.
    """

    name = "gov_wales_consultations"
    source_kind = "consultation"

    # Ten to a page, newest publication first. Page 5 reaches back to April, so
    # eight pages covers anything still open by a wide margin — consultations
    # here run eight to twelve weeks.
    MAX_PAGES = 8

    # Bounds a run when the Welsh Government has had a busy quarter.
    #
    # This was 25, and 25 was wrong. The register is walked newest-first, so a
    # budget smaller than the number of open consultations silently drops the
    # OLDEST ones — which are precisely the ones closing soonest. On the first
    # live run it cost the Council Tax Reduction Scheme consultation, closing
    # in twelve days. Only open consultations are fetched, and there are rarely
    # more than thirty of those, so this is a genuine ceiling rather than a
    # throttle.
    MAX_DETAILS = 60

    def collect(self):
        budget = self.MAX_DETAILS
        seen: set[str] = set()

        for page in range(self.MAX_PAGES):
            url = CONSULTATIONS_PAGE if page == 0 else f"{CONSULTATIONS_PAGE}?page={page}"
            html = self.fetcher.get_text(url)

            if html is None:
                if page == 0:
                    self.note_error(
                        "The Welsh Government consultation register at "
                        f"{CONSULTATIONS_PAGE} could not be fetched. If this "
                        "is a 403, the CloudFront datacentre-IP block that "
                        "used to cover this host has returned, and the "
                        "authoritative closing dates are no longer visible. "
                        "The mailbox route in WELSH-GOVERNMENT-SETUP.md is "
                        "the durable answer when that happens.")
                return

            entries = self._parse_listing(html)
            if page == 0 and not entries:
                self.note_error(
                    "The Welsh Government consultation register returned a "
                    "page but no consultations could be read from it — the "
                    "markup has probably changed. The parser expects "
                    "'li.index-list__item' with '.index-list__title' and "
                    "'.index-list__type'. Until this is fixed, Welsh "
                    "Government consultations are missing rather than absent.")
                return
            if not entries:
                return

            for entry in entries:
                if entry["slug"] in seen or not entry["open"]:
                    continue
                seen.add(entry["slug"])
                if budget <= 0:
                    return
                budget -= 1
                if item := self._detail_to_item(entry):
                    yield item

    # -- parsing -----------------------------------------------------------

    def _parse_listing(self, html: str) -> list[dict]:
        soup = BeautifulSoup(html, "html.parser")
        entries: list[dict] = []

        for node in soup.select("li.index-list__item"):
            link = node.select_one(".index-list__title a") or node.select_one("a[href]")
            if not link:
                continue
            href = (link.get("href") or "").strip()
            if not href or href.startswith("#"):
                continue
            title = _one_line(link.get_text(" ", strip=True))
            if not title:
                continue

            type_el = node.select_one(".index-list__type")
            status = _clean(type_el.get_text(" ", strip=True)) if type_el else ""
            meta_el = node.select_one(".index-list__meta")
            meta = _clean(meta_el.get_text(" ", strip=True)) if meta_el else ""

            entries.append({
                "title": title,
                "url": href if href.startswith("http") else f"https://www.gov.wales{href}",
                "slug": href.rstrip("/").rsplit("/", 1)[-1],
                # "Open consultation" / "Closed consultation". A closed one is
                # of no use in a forward look and must never appear on the page
                # with a countdown beside it.
                "open": status.lower().startswith("open"),
                "meta": meta,
            })
        return entries

    def _detail_to_item(self, entry: dict) -> Item | None:
        html = self.fetcher.get_text(entry["url"])
        if html is None:
            return None

        soup = BeautifulSoup(html, "html.parser")
        main = soup.find("main") or soup.body or soup
        # Navigation and the cookie banner are not consultation text, and a
        # stray "housing" in a site-wide menu would score every page alike.
        for junk in main.select("nav, header, footer, script, style"):
            junk.decompose()
        body = _clean(main.get_text("\n", strip=True))[:6000]

        deadline = parse_deadline(body)
        combined = f"{entry['title']}\n{body}"

        return Item(
            source_kind="consultation",
            source_name="Welsh Government — Consultation",
            title=entry["title"],
            body=combined,
            url=entry["url"],
            # The register shows the publication date; the closing date is the
            # one that matters and it is parsed from the page itself.
            item_date=None,
            forum="Welsh Government",
            agenda_item=entry["meta"],
            deadline=deadline,
            raw_ref=f"consultations:{entry['slug']}",
        )
